# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and test code

on: [pull_request]

env:
  PORT: ${{ secrets.PORT }}
  DB_URI: ${{ secrets.DB_URI }}
  BASE_URL: ${{ secrets.BASE_URL }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule - at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile

      - name: Create environment files
        run: |
          cat << EOF > ./apps/web/.env
          PORT=${{ secrets.PORT }}
          DB_URI=${{ secrets.DB_URI }}
          BASE_URL=${{ secrets.BASE_URL }}
          NODE_ENV=${{ secrets.NODE_ENV }}
          EOF

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
    # - run: pnpm test
